public class ThisWeeksTCMDealsController{
/*
  public List<Deal_Meeting_Association__c> getTheWeeksTCMDeals() {
      List<Deal_Meeting_Association__c> TCMDeal; 
      TCMDeal = [select 
                           Id,
                           TCM_Related_Meeting_Name__c,
                           TWS_TC_Deal_Name__c, 
                           TWS_TC_Deal_Customer__c, 
                           TWS_TC_Category__c, 
                           TWS_TC_Reason__c, 
                           TWS_TC_Deal_Make__c, 
                           TCM_Related_Configurations_Count__c, 
                           TCM_Related_Meeting_Date__c,
                           TCM_Link_to_Related_Oppty__c,
                           TWS_TC_Deal__r.RecordType.DeveloperName,
                           TWS_TC_Deal__r.Description,
                           TWS_TC_Deal__r.NAD__c,
                           TWS_TC_Deal__r.NAE__c,
                           TWS_TC_Deal__r.DistrictManager__r.Name,
                           TWS_TC_Deal__r.RGM__c,
                           Link_to_Related_Oppty_Record__c from Deal_Meeting_Association__c 
           where TCM_Related_Deal_Stage__c = 'Added to TCM' and 
                 TCM_Related_Meeting_Date__c = NEXT_N_DAYS:7];
      
      return TCMDeal;      
  }
  */      
}