var TWSHeader= {};

TWSHeader.populateHeader = function(dealType, data){

  switch(dealType) {

    case 'National':
        TWSHeader.getNationalHeader(data);
        break;
    case 'International':
        TWSHeader.getInternationalHeader(data);
        break;
    case 'Canadian':
        TWSHeader.getCanadianHeader(data);
        break;
    case 'Domestic':
        TWSHeader.getDomesticHeader(data);
        break;
    case 'Sales Proposal':
        TWSHeader.getDomesticHeader(data);
        break;
  }
}

TWSHeader.getNationalHeader = function(data){

  var headerHTML = '';

  if (data){

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular">DOA Initiator</div>'
    headerHTML+= '  <div id="tws_headerDOAInitials" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular"></div>'
    headerHTML+= '  <div id="tws_headerOpptyName" class="slds-col--padded slds-size--6-of-12 slds-medium-size--6-of-12 slds-large-size--8-of-12  slds-align--absolute-center slds-text-heading--medium"></div>'
    headerHTML+= '  <div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular tws_dealNumberText">Deal Number</div>'
    headerHTML+= '  <div id="tws_headerDealNumber" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular tws_dealNumberText"></div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--10-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular tws_borderBottomStrong">'

    headerHTML+= '      <table class="tws_headerSection1">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:20%;">Customer:</td>'
    headerHTML+= '              <td id="tws_headerCustomer" style="width:60%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">Spec #</td>'
    headerHTML+= '              <td id="tws_headerSpecNumber" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:10%;">Cust.City, State</td>'
    headerHTML+= '              <td id="tws_headerCustomerCityState" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">SOC:</td>'
    headerHTML+= '              <td id="tws_headerDealerCode" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">District Manager:</td>'
    headerHTML+= '              <td id="tws_headerDistrictManager" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'


    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection2">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Request Delivery From:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Order Received From:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection3">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Price Protect:</td>'
    headerHTML+= '              <td id="tws_headerPriceProtect" style="width:25%;"></td>'
    headerHTML+= '              <td style="width:25%;">Competition:</td>'
    headerHTML+= '              <td id="tws_headerCompetition" style="width:25%;"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '  </div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--2-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <table class="tws_headerSection4">'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">TC Date</td>'
    headerHTML+= '          <td id="tws_headerTCDate" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Date Prepared</td>'
    headerHTML+= '          <td  id="tws_headerDatePrepared" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">New/ Revision</td>'
    headerHTML+= '          <td id="tws_headerNewOrRevision" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Revision Date</td>'
    headerHTML+= '          <td id="tws_headerRevisionDate style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '  </table>'
    headerHTML+= '</div>'

    $('#tws_insideMainContainer').prepend(headerHTML);
  }
}

TWSHeader.getInternationalHeader = function(data){

  var headerHTML = '';

  if (data){

    headerHTML+= '<div id="tws_headerOpptyName" class="slds-col--padded slds-size--6-of-12 slds-medium-size--6-of-12 slds-large-size--8-of-12  slds-align--absolute-center slds-text-heading--medium"></div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--10-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular tws_borderBottomStrong">'

    headerHTML+= '      <table class="tws_headerSection1">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:20%;">Customer:</td>'
    headerHTML+= '              <td id="tws_headerCustomer" style="width:80%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:20%;">Country:</td>'
    headerHTML+= '              <td id="tws_headerCountry" style="width:80%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'


    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection2">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Request Delivery From:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Order Received From:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '  </div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--2-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <table class="tws_headerSection4">'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Date</td>'
    headerHTML+= '          <td id="tws_headerTCDate" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Date Prepared</td>'
    headerHTML+= '          <td  id="tws_headerDatePrepared" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">New/ Revision</td>'
    headerHTML+= '          <td id="tws_headerNewOrRevision" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Revision Date</td>'
    headerHTML+= '          <td id="tws_headerRevisionDate style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '  </table>'
    headerHTML+= '</div>'

    $('#tws_insideMainContainer').prepend(headerHTML);
  }
}

TWSHeader.getCanadianHeader = function(data){

  var headerHTML = '';

  if (data){

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular">DOA Initiator</div>'
    headerHTML+= '  <div id="tws_headerDOAInitials" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular"></div>'
    headerHTML+= '  <div id="tws_headerOpptyName" class="slds-col--padded slds-size--6-of-12 slds-medium-size--6-of-12 slds-large-size--8-of-12  slds-align--absolute-center slds-text-heading--medium"></div>'
    headerHTML+= '  <div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular tws_dealNumberText">Deal Number</div>'
    headerHTML+= '  <div id="tws_headerDealNumber" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular tws_dealNumberText"></div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--10-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular tws_borderBottomStrong">'

    headerHTML+= '      <table class="tws_headerSection1">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:20%;">Customer:</td>'
    headerHTML+= '              <td id="tws_headerCustomer" style="width:60%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">MY</td>'
    headerHTML+= '              <td id="tws_headerModelYear" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:10%;">Cust.City, State</td>'
    headerHTML+= '              <td id="tws_headerCustomerCityState" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">SOC:</td>'
    headerHTML+= '              <td id="tws_headerDealerCode" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">District Manager:</td>'
    headerHTML+= '              <td id="tws_headerDistrictManager" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'


    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection2">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Request Delivery From:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Order Received From:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection3">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Price Protect:</td>'
    headerHTML+= '              <td id="tws_headerPriceProtect" style="width:25%;"></td>'
    headerHTML+= '              <td style="width:25%;">Competition:</td>'
    headerHTML+= '              <td id="tws_headerCompetition" style="width:25%;"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '  </div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--2-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <table class="tws_headerSection4">'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">TC Date</td>'
    headerHTML+= '          <td id="tws_headerTCDate" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Date Prepared</td>'
    headerHTML+= '          <td  id="tws_headerDatePrepared" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">New/ Revision</td>'
    headerHTML+= '          <td id="tws_headerNewOrRevision" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Revision Date</td>'
    headerHTML+= '          <td id="tws_headerRevisionDate style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '  </table>'
    headerHTML+= '</div>'

    $('#tws_insideMainContainer').prepend(headerHTML);
  }
}

TWSHeader.getDomesticHeader = function(data){

  var headerHTML = '';

  if (data){

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular">DOA Initiator</div>'
    headerHTML+= '  <div id="tws_headerDOAInitials" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular"></div>'
    headerHTML+= '  <div id="tws_headerOpptyName" class="slds-col--padded slds-size--6-of-12 slds-medium-size--6-of-12 slds-large-size--8-of-12  slds-align--absolute-center slds-text-heading--medium"></div>'
    headerHTML+= '  <div class="slds-col--padded slds-size--1-of-12 slds-medium-size--1-of-12 slds-large-size--1-of-12 slds-text-body--regular tws_dealNumberText">Deal Number</div>'
    headerHTML+= '  <div id="tws_headerDealNumber" class="slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-large-size--1-of-12  slds-text-body--regular tws_dealNumberText"></div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--10-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular tws_borderBottomStrong">'

    headerHTML+= '      <table class="tws_headerSection1">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:20%;">Customer:</td>'
    headerHTML+= '              <td id="tws_headerCustomer" style="width:60%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">MY</td>'
    headerHTML+= '              <td id="tws_headerModelYear" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:10%;">Cust.City, State</td>'
    headerHTML+= '              <td id="tws_headerCustomerCityState" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">SOC:</td>'
    headerHTML+= '              <td id="tws_headerDealerCode" style="width:10%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:10%;">District Manager:</td>'
    headerHTML+= '              <td id="tws_headerDistrictManager" style="width:30%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'


    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection2">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Request Delivery From:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerReqDeliveryTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Order Received From:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedFrom" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '              <td style="width:25%;">To:</td>'
    headerHTML+= '              <td id="tws_headerOrderReceivedTo" style="width:25%;" class="tws_borderBottom"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
    headerHTML+= '      <table class="tws_headerSection3">'
    headerHTML+= '        <tr><td>'
    headerHTML+= '          <table>'
    headerHTML+= '            <tr>'
    headerHTML+= '              <td style="width:25%;">Price Protect:</td>'
    headerHTML+= '              <td id="tws_headerPriceProtect" style="width:25%;"></td>'
    headerHTML+= '              <td style="width:25%;">Competition:</td>'
    headerHTML+= '              <td id="tws_headerCompetition" style="width:25%;"></td>'
    headerHTML+= '            </tr>'
    headerHTML+= '          </table>'
    headerHTML+= '        </td></tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </div>'
    headerHTML+= '  </div>'
    headerHTML+= '</div>'

    headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--2-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
    headerHTML+= '  <table class="tws_headerSection4">'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">TC Date</td>'
    headerHTML+= '          <td id="tws_headerTCDate" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Date Prepared</td>'
    headerHTML+= '          <td  id="tws_headerDatePrepared" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">New/ Revision</td>'
    headerHTML+= '          <td id="tws_headerNewOrRevision" style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '    </td></tr>'
    headerHTML+= '    <tr><td>'
    headerHTML+= '      <table>'
    headerHTML+= '        <tr>'
    headerHTML+= '          <td style="width:50%;">Revision Date</td>'
    headerHTML+= '          <td id="tws_headerRevisionDate style="width:50%;" class="tws_borderBottom"></td>'
    headerHTML+= '        </tr>'
    headerHTML+= '      </table>'
    headerHTML+= '  </table>'
    headerHTML+= '</div>'

    $('#tws_insideMainContainer').prepend(headerHTML);
  }
}

/*

  headerHTML+= '<div id="tws_headerTitle" class="slds-col--padded slds-size--1-of-1">'
  headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '    <div class="slds-col--padded slds-size--1-of-12 slds-text-body--regular">DOA Initiator</div>'
  headerHTML+= '    <div id="tws_headerDOAInitials" class="slds-col--padded slds-size--1-of-12 slds-text-body--regular"></div>'
  headerHTML+= '    <div id="tws_headerOpptyName" class="slds-col--padded slds-size--8-of-12 slds-align--absolute-center slds-text-heading--medium"></div>'
  headerHTML+= '    <div class="slds-col--padded slds-size--1-of-12 slds-text-body--regular tws_dealNumberText">Deal Number</div>'
  headerHTML+= '    <div id="tws_headerDealNumber" class="slds-col--padded slds-size--1-of-12 slds-text-body--regular tws_dealNumberText"></div>'
  headerHTML+= '  </div>'
  headerHTML+= '</div>'

  headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--10-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
  headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular tws_borderBottomStrong">'
  headerHTML+= '      <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '        <div class="tws_nationalSpecific tws_domesticSalesProposalSpecific tws_domesticSpecific tws_canadaSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">Customer:</div>'
  headerHTML+= '        <div class="tws_internationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--4-of-12 slds-text-body--regular slds-m-top--xx-small">Customer:</div>'
  headerHTML+= '        <div id="tws_headerCustomer" class="slds-col--padded slds-size--5-of-6 slds-medium-size--8-of-12 slds-text-align--center slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '        <div class="tws_domesticSalesProposalSpecific tws_domesticSpecific tws_canadaSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--1-of-12 slds-text-body--regular slds-m-top--xx-small">MY:</div>'
  headerHTML+= '        <div class="tws_nationalSpecific slds-col--padded slds-text-body--regular slds-m-top--xx-small slds-size--1-of-6 slds-medium-size--1-of-12">Spec #</div>'
  headerHTML+= '        <!--<div class="tws_internationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12">&nbsp;</div>-->'
  headerHTML+= '        <div id="tws_headerModelYear" class="tws_domesticSalesProposalSpecific tws_domesticSpecific tws_canadaSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--1-of-12 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '        <div id="tws_headerSpecNumber" class="tws_nationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--1-of-12 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '        <div class="tws_canadaSpecific tws_domesticSalesProposalSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">Cust.City, State</div>'
  headerHTML+= '        <div id="tws_headerCustomerCityState" class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--3-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small tws_borderBottom"></div>'
  headerHTML+= '        <div class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">SOC:</div>'
  headerHTML+= '        <div id="tws_headerDealerCode" class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small"></div>'
  headerHTML+= '        <div class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--1-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">District Manager:</div>'
  headerHTML+= '        <div id="tws_headerDistrictManager" class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--3-of-6 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small tws_borderBottom"></div>'
  headerHTML+= '        <div class="tws_internationalSpecific slds-col--padded slds-size--2-of-12 slds-medium-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">Country:</div>'
  headerHTML+= '        <div id="tws_headerCountry" class="tws_internationalSpecific slds-text-align--center slds-medium-size--10-of-12 slds-col--padded slds-size--10-of-12 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '      </div>'
  headerHTML+= '    </div>'
  headerHTML+= '    <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
  headerHTML+= '      <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '        <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
  headerHTML+= '          <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '            <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small">Request Delivery From:</div>'
  headerHTML+= '            <div id="tws_headerReqDeliveryFrom" class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '            <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small">To:</div>'
  headerHTML+= '            <div id="tws_headerReqDeliveryTo" class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '            <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small">Order Received From:</div>'
  headerHTML+= '            <div id="tws_headerOrderReceivedFrom" class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small tws_borderBottom"></div>'
  headerHTML+= '            <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small">To:</div>'
  headerHTML+= '            <div id="tws_headerOrderReceivedTo" class="slds-col--padded slds-size--3-of-12 slds-medium-size--3-of-12 slds-text-body--regular slds-m-top--xx-small tws_borderBottom"></div>'
  headerHTML+= '          </div>'
  headerHTML+= '        </div>'
  headerHTML+= '        <div class="slds-col--padded slds-size--1-of-1 slds-text-body--regular">'
  headerHTML+= '          <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '            <div class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">Price Protect:</div>'
  headerHTML+= '            <div id="tws_headerPriceProtect" class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--2-of-12 slds-text-body--regular slds-m-top--xx-small"></div>'
  headerHTML+= '            <div class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--2-of-12 slds-text-body--regular slds-m-top--xx-small">Competition:</div>'
  headerHTML+= '            <div id="tws_headerCompetition" class="tws_domesticSalesProposalSpecific tws_canadaSpecific tws_domesticSpecific tws_nationalSpecific slds-col--padded slds-size--2-of-12 slds-text-body--regular slds-m-top--xx-small"></div>'
  headerHTML+= '          </div>'
  headerHTML+= '        </div>'
  headerHTML+= '      </div>'
  headerHTML+= '    </div>'
  headerHTML+= '  </div>'
  headerHTML+= '</div>'
  headerHTML+= '<div class="slds-col--padded slds-size--1-of-1 slds-medium-size--10-of-12 slds-large-size--2-of-12 tws_borderAllStrong tws_heightToAdjust" data-name="headerCol">'
  headerHTML+= '  <div class="slds-grid slds-wrap slds-grid--pull-padded">'
  headerHTML+= '      <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular slds-m-top--xx-small">TC Date</div>'
  headerHTML+= '      <div id="tws_headerTCDate" class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '      <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular slds-m-top--xx-small">Date Prepared</div>'
  headerHTML+= '      <div  id="tws_headerDatePrepared" class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '      <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular slds-m-top--xx-small">New/ Revision</div>'
  headerHTML+= '      <div id="tws_headerNewOrRevision" class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '      <div class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular slds-m-top--xx-small">Revision Date</div>'
  headerHTML+= '      <div id="tws_headerRevisionDate" class="slds-col--padded slds-size--3-of-12 slds-medium-size--1-of-2 slds-text-body--regular tws_borderBottom slds-m-top--xx-small"></div>'
  headerHTML+= '  </div>'
  headerHTML+= '</div>'

  */
